const skills = [
    { name: "HTML", icon: "/icons/html.svg" },
    { name: "CSS", icon: "/icons/css.svg" },
    { name: "WordPress", icon: "/icons/wordpress.svg" },
    { name: "JavaScript", icon: "/icons/javascript.svg" },
    { name: "TypeScript", icon: "/icons/typescript.svg" },
    { name: "React", icon: "/icons/react.svg" },
    { name: "TailwindCSS", icon: "/icons/tailwind.svg" },
    { name: "Node.js", icon: "/icons/nodejs.svg" },
    { name: "NPM", icon: "/icons/npm.svg" },
    { name: "Expressjs", icon: "/icons/express.svg" },
    { name: "Git", icon: "/icons/git.svg" },
    { name: "Docker", icon: "/icons/docker.svg" },
    { name: "Firebase", icon: "/icons/firebase.svg" },
    { name: "PHP", icon: "/icons/php.svg" },
    { name: "PostgreSQL", icon: "/icons/postgresql.svg" },
    { name: "MariaDB", icon: "/icons/mariadb.svg" },
    { name: "Prisma", icon: "/icons/prisma.svg" },
    { name: "WebStorm", icon: "/icons/webstorm.svg" },
    { name: "PHPStorm", icon: "/icons/phpstorm.svg" },
    { name: "VSCode", icon: "/icons/vscode.svg" },
    { name: "Vite", icon: "/icons/vite.svg" },
    { name: "React-Router-Dom", icon: "/icons/react-router.svg" },
    { name: "JWT", icon: "/icons/jwt.svg" },
    { name: "Socket.io", icon: "/icons/socket.svg" },
];

export default skills;